name: Suggested Resource
description: Suggest a resource to add to this project
title: "[Suggested]: "
labels: ["suggested"]
assignees:
  - georgemandis
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: The name of the website
      placeholder: ex. Frobozz Remote Jobs
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: The URL for the website, preferably the landing page where jobs are actually listed
      placeholder: ex. https://frobozzcojobs.com/remote
    validations:
      required: true      
  - type: input
    id: feed
    attributes:
      label: Feed URL
      description: A link to the primary RSS or JSON feed for job listings
      placeholder: https://frobozzcojobs.com/rss.xml
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Anything else worth mentioning. 
      placeholder: ex. Optional URL parameters for feeds, other means to subscribe if no feed is present, other limitations or specificty in jobs posted (optional)
